#!/bin/sh
function retry()
{
        local n=0
        local try=${WGET_TRIES:-20}
        local cmd="${@: 1}"
        local last_exit=0

        until [[ $n -ge $try ]]
        do
                $cmd && break || {
                        last_exit=$?
                        n=$(expr "$n" + 1)
                        sleep 1;
                        }
        done
	return $last_exit
}

retry /bin/wget $@
